# Generated by Django 4.1.7 on 2023-03-08 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
